/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.view.statistical;

import com.edusys.view.manager.CourseManager;
import com.edusys.view.manager.EmployeeManager;
import com.edusys.view.manager.LearnerManage;
import com.edusys.view.manager.MajorManager;
import com.edusys.view.manager.ManagerForm;
import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.border.EmptyBorder;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author ADMIN
 */
public class StaticalForm extends javax.swing.JPanel {

    
    static class SUB_STATISTICAL_MANAGER {
        static int LEARNER= 0;
        static int POINT_IN_COURSE = 1;
        static int POINT_IN_MAJOR = 2;
        static int REVENUE = 3;
    }
    
    private LearnerStatical learnerStatistical ;
    private PointInCourseStatistical pointInCoures ;
    private PointInMajorStatistical pointInMajor ;
    private RevenueStatistical revenueStatistical;
     private MigLayout layout;
    
    private int index = 0;
    
    
    /**
     * Creates new form StaticalForm
     */
    public StaticalForm() {
        initComponents();
        
        
           setOpaque(false);
        setLayout(new BorderLayout());
        setBorder(new EmptyBorder(10, 20, 10, 20));
        tabPane.setOpaque(false);

        layout = new MigLayout("fill", "0[]0[100%, fill]0", "0[fill, top]0");
        setLayout(layout);
        
        
        learnerStatistical = new LearnerStatical();
        add(tabPane, "h 70!, wrap");
        add(learnerStatistical, "w 100%, h 100%");

    }
    
    
       public void tabSelected(int index){
        if (index == SUB_STATISTICAL_MANAGER.LEARNER){
            learnerStatistical = new LearnerStatical();
            showForm(learnerStatistical);
        }else if (index == SUB_STATISTICAL_MANAGER.POINT_IN_COURSE){
            pointInCoures = new PointInCourseStatistical();
            showForm(pointInCoures);
        }else if (index == SUB_STATISTICAL_MANAGER.POINT_IN_MAJOR){
           pointInMajor = new PointInMajorStatistical();
            showForm(pointInMajor);
        }else if (index ==SUB_STATISTICAL_MANAGER.REVENUE ){
            revenueStatistical = new RevenueStatistical();
            showForm(revenueStatistical);
        }
    }
       
       
     public void showForm(Component form) {
        remove(getComponentCount()-1);
        add(form, "w 100%, h 100%");
        repaint();
        revalidate();
    }        
      
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane = new javax.swing.JPanel();
        btnLearnerStatistical = new com.ui.swing.component.Tab();
        jLabel1 = new javax.swing.JLabel();
        btnPointInCourse = new com.ui.swing.component.Tab();
        jLabel5 = new javax.swing.JLabel();
        btnPointInMajor = new com.ui.swing.component.Tab();
        jLabel6 = new javax.swing.JLabel();
        btnRevenue = new com.ui.swing.component.Tab();
        jLabel7 = new javax.swing.JLabel();

        tabPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPaneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabPaneMousePressed(evt);
            }
        });

        btnLearnerStatistical.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLearnerStatisticalMouseClicked(evt);
            }
        });
        btnLearnerStatistical.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Người học");
        btnLearnerStatistical.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 7, -1, 30));

        btnPointInCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPointInCourseMouseClicked(evt);
            }
        });
        btnPointInCourse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bảng điểm");
        btnPointInCourse.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 7, -1, 30));

        btnPointInMajor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPointInMajorMouseClicked(evt);
            }
        });
        btnPointInMajor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Điểm chuyên ngành");
        btnPointInMajor.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, -1));

        btnRevenue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRevenueMouseClicked(evt);
            }
        });
        btnRevenue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Doanh thu");
        btnRevenue.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        javax.swing.GroupLayout tabPaneLayout = new javax.swing.GroupLayout(tabPane);
        tabPane.setLayout(tabPaneLayout);
        tabPaneLayout.setHorizontalGroup(
            tabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaneLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnLearnerStatistical, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnPointInCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnPointInMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(702, Short.MAX_VALUE))
        );
        tabPaneLayout.setVerticalGroup(
            tabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLearnerStatistical, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPointInCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPointInMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 777, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
     
    
    
    
    
    private void btnLearnerStatisticalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLearnerStatisticalMouseClicked

        btnLearnerStatistical.clear();
        btnPointInCourse.clear();
        btnPointInMajor.clear();
        btnRevenue.clear();

        btnLearnerStatistical.click();
        tabSelected(SUB_STATISTICAL_MANAGER.LEARNER);
    }//GEN-LAST:event_btnLearnerStatisticalMouseClicked

    private void btnPointInCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPointInCourseMouseClicked

        btnLearnerStatistical.clear();
        btnPointInCourse.clear();
        btnPointInMajor.clear();
        btnRevenue.clear();

        btnPointInCourse.click();
        tabSelected(SUB_STATISTICAL_MANAGER.POINT_IN_COURSE);
    }//GEN-LAST:event_btnPointInCourseMouseClicked

    private void btnPointInMajorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPointInMajorMouseClicked

        btnLearnerStatistical.clear();
        btnPointInCourse.clear();
        btnPointInMajor.clear();
        btnRevenue.clear();

        btnPointInMajor.click();
        tabSelected(SUB_STATISTICAL_MANAGER.POINT_IN_MAJOR);
    }//GEN-LAST:event_btnPointInMajorMouseClicked

    private void btnRevenueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevenueMouseClicked

        btnLearnerStatistical.clear();
        btnPointInCourse.clear();
        btnPointInMajor.clear();
        btnRevenue.clear();

        btnRevenue.click();
        tabSelected(SUB_STATISTICAL_MANAGER.REVENUE);
    }//GEN-LAST:event_btnRevenueMouseClicked

    private void tabPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPaneMouseClicked

    }//GEN-LAST:event_tabPaneMouseClicked

    private void tabPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPaneMousePressed

        btnRevenue.clear();
    }//GEN-LAST:event_tabPaneMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ui.swing.component.Tab btnLearnerStatistical;
    private com.ui.swing.component.Tab btnPointInCourse;
    private com.ui.swing.component.Tab btnPointInMajor;
    private com.ui.swing.component.Tab btnRevenue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel tabPane;
    // End of variables declaration//GEN-END:variables
}
